### ISSUE TITLE
Destroy stack informations

### ISSUE THREAD

**Issue by thomasdesplaces** [aws-samples/water-tank-digital-twin#11]
Hi everybody,

In your documentation, I don't see anything about the destruction of the stack (like `npm run destroy`).

When I read *package.json* I supposed that I have to enter `npm run cdk destroy` but this command do nothing ...

Could you please update the documentation ?

Regards

**Comment by flochaz** [comment]
Thx @thomasdesplaces , indeed , we will add that asap
